### PR TITLE
De-bug estimability

### PR DESCRIPTION
**Pull request by mchlshort**
Fixed some issues that were resulting in strange behaviour in the estimability analysis and including the latest version of the documentation.

Also included are some data tools that somehow didn't make it into the last pull from the previous branch.

### CODE REVIEW

**Comment by schenkch** [comment]
@mchlshort: I just ran the tests and paper_example_1.py fails. 

File "paper_example_1.py", line 234, in <module>
    results_pyomo = p_estimator.run_param_est_with_subset_lambdas(builder_before_data, end_time, new_subs, nfe, ncp, sigmas, solver= 'k_aug')
TypeError: run_param_est_with_subset_lambdas() got an unexpected keyword argument 'solver'

I think we should put the paper examples in a different folder as well.

**Comment by mchlshort** [comment]
Ah, I see that... I forgot I made a change to that module. I will fix that now and also move the paper examples to another folder within the repo

**Comment by mchlshort** [comment]
Hi Christina, thanks for catching the error, everything should be good now. 

I think that this is pretty much the full version for the paper now. We just need your latest stuff in the documentation and the example for the paper and then we should be all good.

**Comment by schenkch** [comment]
Hi Mike, 
Thanks. I just do not understand why you did that force-push up there and changed my previous change back again.

**Comment by mchlshort** [comment]
Yeah, that was my fault... My version was behind that commit and my git wouldn't upload without pulling the old version and I kept getting a bug where my version management software would freeze. It was faster to just force push and deal with that single conflict. Sorry!

**Review by schenkch — APPROVED** [review]
All good now and ready to be merged.

**Comment by mchlshort** [comment]
Thanks Christina!

**Pull request merged**
