### PR TITLE
Estimation refactor

### PR DESCRIPTION
**Pull request by kwmcbride**
This version of EstimationPotential uses pynumero instead of k_aug for calculating the reduced Hessian. The previous version relied on debug files from k_aug which may not be available to users and is also not the intended use. This new version should present no issues to the users.

The tutorial documentation has been updated to reflect this change.

### CODE REVIEW

**Comment by mchlshort** [comment]
This looks great! I can do a detailed review and merge on the weekend.

**Comment by kwmcbride** [comment]
I just pushed another branch to my repo with EstimationPotential rewritten to use a model instead of the build templates. By doing this, I could reduce large amounts of code and make it simpler. If you also have time, you could look at the estimation_refactor_model branch as well. I will wait to do a pull request or close this one.

**Comment by mchlshort** [comment]
That sounds good. So does that branch include these commits too? If so then I can just run all the tests and check that one. Then if you do the pull request on that one I will approve immediately. I was planning on doing this tomorrow morning, but if I don't get to it then I will on Sunday morning.

**Comment by kwmcbride** [comment]
It has the commits, so just use the new branch then.

**Comment by mchlshort** [comment]
Hi @kwmcbride, I did the tests and got failures for Ex_10, both Ex_16s and the Dow problem. From what I can tell, here are the issues (all small things that are easy to fix):

**Ex_10:** it failed the test, but it worked when I ran it manually and skipped one of the estimations. I think that you can fix this by lowering the tolerance for convergence. What was strange here was that there was a new print, which I didn't remember that had the initial values printed twice and all set to zero. Can you check that out please?

**Ex16**: This was just that I didn't have one of the packages required for pynumero. Can you please add the required packages to the requirements.txt and also in the setup.py file (I usually just use this one and it works fine)

**Dow problem**: This one is just missing data.

Maybe it is best if I close the PR and then you can open a new one with the branch I checked - "estimation_refactor_model" once these have been ironed out? Its looking really good otherwise!

**Comment by kwmcbride** [comment]
Thanks for testing. I find the error with Example 10 to be very strange considering I made no changes to any module that affects it. I don't see this error in my version.

Which package are you missing for pynumero exactly? Isn't it contained within pyomo?

Also, the Dow_Estimability and the Ex_CSTR_estimability_temperature_concentration examples should be deleted.

I am going to delete this branch anyway, the estimation_refactor_model is much further along in development.

**Pull request closed without merging**
