### PR TITLE
All new features for first stable release now

### PR DESCRIPTION
**Pull request by schenkch**
**New Features**
Can now fix the device variance in VarianceEstimator

Useful for problems where the variance estimation algorithm struggles to converge to useful variance values, putting too much variance into the instrument. Also useful if manufacturer provides variance of instrument.
Can now read spectra directly from device CSV

#68
While it doesn't allow data to be read from other file types, it automatically transforms timestamped data into seconds and also can be used to remove negative values
New data_tools

New data tools for baseline shift, removing negative values and removing certain wavelengths to decrease problem size.
Added ability to set bounds on certain profiles

#93
This is a really useful new feature for when we know of certain peak behaviour or know that a certain species' concentration does not go below a certain value.

**Minor additions**

- can now ask to report time spent on variance estimator and parameter estimator
- added using ipopt for least squares into a standard example as it is actually faster and users did not have an example of its implementation.
- fixed issue in variance estimator where solver options were not passed onto suboptimizations correctly
- spotted the use of the wrong keyword in example for variance estimation ("solver_options" instead of "solver_opts"
- spotted and fixed issue where negative D values were not being sensed by the VarianceEstimator and therefore the S matrix was still bounded to 0.

A new example runs through some of these options.

**Other fixes and extensions:**

When solving the optimization problem the user can now use the ipopt warmstart option as well, such that we can use the dual variables from a previous problem for the solution of the current problem.

Lack of fit tool works for non-absorbing species case as well now. 

A new structure was implemented for the case with non-absorbing species. They are not included in the S matrix any more and are taken out of the first term in the objective of the parameter estimation problem. The user interface is still the same. The changes were just added in the backend. 

New documentation still to come

### CODE REVIEW

**Comment by schenkch** [comment]
@mchlshort  I resolved all the conflicts and ran the validate_tut_problems.py. They were successful. This version contains all our changes now. Can you please test this again on your machine before merging?

**Review by mchlshort — APPROVED** [review]
Looks good and passes all the tests. Thanks!

**Comment by mchlshort** [comment]
All looks good to me. @schenkch - Just quick question about what you mean by "lack of fit estimator"? Is this the wavelength selection or just the lack of fit tool?

**Comment by schenkch** [comment]
I just meant the lack of fit tool. I changed it in the description above.

**Pull request merged**
