### PR TITLE
Structure for inclusion of H/UPLC data

### PR DESCRIPTION
**Pull request by schenkch**
- Addition of option to take H/UPLC data with just liquids or liquids and solids into account
- Addition of option for L2 penalty term for penalizing values deviating from the defined optimal parameter values in the objective of the parameter estimation problem
- Addition of option to read values for mutable parameter from file, interpolate and use in the modeling context
- Addition of option to write eigenvalues of reduced Hessian automatically to a file
- Fixed bugs and other small enhancements

### CODE REVIEW

**Comment by mchlshort** [comment]
Hi Christina,

I ran the tests and everything seems good. It is impossible for me to test the new additions though as we don't have any examples including the H/UPLC data. 

Could you maybe make a test case including that and also to add this to the documentation so that I can work through what the code does exactly? We can chat about it when you are in, but for now I will just leave this open.

**Comment by schenkch** [comment]
Hi Mike, 
As promised I added the penalty and eigenvalues of the reduced Hessian options to the documentation, such that it can be merged for now and I will try to document the other things and create an example for that next week. 
Thanks.

**Comment by schenkch** [comment]
Hi Mike, 
I resolved the conflicts and the tests were successful as well. 
Should be all good to go now. 
Thanks.

**Review by mchlshort — APPROVED** [review]
Seems ok to me. Nice work @schenkch !

**Pull request merged**
