### PR TITLE
New IPOPT installation instructions for Windows

### PR DESCRIPTION
**Pull request by mchlshort**
This just replaces the outdated IPOPT installation instructions with a new document that is tested on numerous Windows 10 machines.

### CODE REVIEW

**Review by kwmcbride — APPROVED** [review]
I see no issue with this. It seems like it was needed.

Apparently I don't have write access.

**Comment by schenkch** [comment]
@kwmcbride, @mchlshort : Did you check them and just need me to approve this because I have write access or is it better if I check them again? What do you think?

**Comment by kwmcbride** [comment]
If you have a windows computer, go ahead and check it out. I don't use windows, but found the instructions to be okay.

Relating to write access: I think it would be good to have that myself at some point.

**Comment by mchlshort** [comment]
> @kwmcbride, @mchlshort : Did you check them and just need me to approve this because I have write access or is it better if I check them again? What do you think?

@schenkch , I have checked them on 3 students' systems, so the instructions should be good. If you could just approve, that would be great.

@kwmcbride You need to have @salvadorgarciamunoz give you that, unfortunately neither @schenkch or myself have permissions to add you. I agree that you should have them.

**Review by schenkch — APPROVED** [review]
Seems to be all good then @mchlshort . I just gave it a quick read but looks good to me, too. 
I just see a problem with them just being for Windows 10 and removing the other ones as some of our users are not using Windows10 yet.

**Pull request merged**
