### PR TITLE
New organization

### PR DESCRIPTION
**Pull request by mchlshort**
Hi Christina,

Could you please have a check on the new branch and run a couple tests. Seems to work my side, but would appreciate a double check before merging.

Thanks,
Mike

### CODE REVIEW

**Comment by schenkch** [comment]
@mchlshort Yeah, sure. I will let you know how it goes.

**Comment by schenkch** [comment]
It looks like the validation script tests work but not the tutorial examples. The import kipet does not work for the tutorial examples and there are functions missing.

**Comment by mchlshort** [comment]
Hmm... They work for me, do they work for you if you try them manually? Wondering why it isn't working.

**Comment by schenkch** [comment]
Yes, I tried that as well and that does not work either. For the Paper/replicate51a example you used import kipet instead of the explicite ones as well and that one failed as well. Did you use Python2 or 3?

**Comment by mchlshort** [comment]
ok, so I think what I will do is revert to the old importing system for now. And then I will create an issue and we can work on the better way to import in a different place. For now I am going to close this pull request and then open a new one so that the new file structure and documentation is merged with the master and Sal can have access to that so that his team can start with the code review asap.

**Pull request closed without merging**
