### PR TITLE
New data

### PR DESCRIPTION
**Pull request by kwmcbride**
This is a big update to KIPET that makes it much easier and cleaner to use for the user. Many of the steps required have been placed into the background. This is not true for each feature and these will be dealt with at a later time. Most of the functions are backwards compatible. The addition of jump points is not backwards compatible and has been rewritten. The major features added or removed are:

1. To use KIPET, you simply need to "import kipet" or "from kipet import KipetModel". Everything that needs to be done can be achieved using the KipetModel class. To see how this works, you can look at all examples in "new_examples". Running the VarianceEstimator and ParameterEstimator instances is now handled automatically and can be influenced using a new settings object (see the examples for this too).

2. A new variable, Cm, is now used to describe the concentration data obtained from data that is not spectral. This allows one to separate the two kinds of information in the objective functions.

3. ResultsObject now has new plotting functions for the results based on plotly, which is now a requirement.

4. The way unknown initial values for components (Pinit) are handled has been completely changed. You simply need to declare when a component is not known (known=False, see AD_13.py in new_examples). There is no need to use a complementary state for these components.

5. Adding dosing points (jump points) is now very simple. See Ex_5 to see how to use this. Work still needs to be done for declaring the algebraic variables used in dosing.

6. The MultipleExperimentsEstimator module is intact, but the new top-level kipet_model module uses MEE_new.py, which is greatly reduced in size. The individual model VE and PE models are handled directly instead of being recreated in the MEE module as it was. This makes the code more concise and easier to change. It is also much easier to use MEE. You simply need to add more than one reaction model to the KipetModel instance. It will handle the rest automatically in the same way as a single model. See Ex_11, Ex_12, AD_13, for example.

7. New classes for handling the data, the model parameters, and model components have been added to simplify code use.

8. There are also many other changes that have been made to the code so that this new version works that are not listed here.

####

I am making this pull request so that the code can be reviewed while I work on the documentation for this new version. I welcome your feedback!

### CODE REVIEW

**Comment by mchlshort** [comment]
Hi @kwmcbride, this looks fantastic and a big improvement! It seems really clean and neat. Unfortunately, I am totally swamped right now. I will try give it a detailed review either some time next week or next weekend.

**Comment by schenkch** [comment]
This looks very impressive @kwmcbride. I did not check it in detail but I just wanted to mention that before merging all of this, it would be good to add the current version to the releases like we did with the last big merge. @mchlshort: If you have the feeling that I should check it as well when going through, just let me know but currently I am too busy with other things.

**Comment by kwmcbride** [comment]
I have updated the documentation now to reflect the changes made to most of the tutorials. There are still a couple of the old examples that do not yet work in the new version and I will need to work on these.

I have added the custom objective capabilities that I discussed in the open issue on this matter.

I have also added some of the changes needed to use Pyomo 5.7 with Kipet. There are still some others I will be adding to this branch just to make it complete.

I do agree that we should make a new release.

Edit: I also moved all of the main modules into a new folder: library/core_modules

**Comment by kwmcbride** [comment]
This is a quote of my response to the latest issue concerning adding data not working:

> I rewrote the entire way KIPET handles directories and committed the changes to the new_data branch. This adds a new file to the kipet directory "settings.txt" that contains some general settings used in KIPET. I will be expanding this file to handle more of the settings to clean up the differences between KipetModel and ReactionModel settings. For the moment, the most important parts are DATA_DIRECTORY and CHART_DIRECTORY. These handle where the data used in model fittings is stored and where generated charts are saved, respectively. Both directories are automatically set when you install KIPET via new additions in the "setup.py" file. You can override these using the settings object in KipetModel, just make sure it's an absolute path to prevent any strange results.
> 
> The new arrangement uses absolute paths at every turn and thus will work from a Jupyter Notebook, in an IDE, or from the command prompt. I have already tested it in each of these.

I would like to know if you have any time to review this pull request. It has been sitting here for four weeks. I ask because there are users who would like to use KIPET, but with this new version on the cusp of happening, it is better if they start with it instead of the previous version.

**Comment by mchlshort** [comment]
Hi @kwmcbride, Thanks for this, it looks great. I will do it this weekend! I have been absolutely swamped lately, but now that AIChE is over I have a bit more breathing space.

**Comment by kwmcbride** [comment]
Thanks! I hope there are not too many issues left to iron out. I will be making mostly cosmetic changes with any following commits. The only big thing I have left to change is the EstimationPotential module. I have written it to work with various methods to check on some issues I though I had. It's implementation will be the same though. I will make a new pull request for this though.

**Comment by mchlshort** [comment]
Hi @kwmcbride, 

My apologies for taking so long to get to this. The past few months have been so crazy here. This is really great and I think that the new version seems far more intuitive and easy to use! Great job! 

I especially like the way that everything is now automatically set up in the background so that users can call functions directly on the KipetModel object. The use of plotly and handling of the concentration data and unknown initial values for components seems to also simplify everything well.

Many thanks for sifting through that MEE code and making it more concise and simple. Apologies for the rather clumsy previous code structure! I also really appreciate the clean and simple file structure now.

I am making this pull request so that the code can be reviewed while I work on the documentation for this new version. I welcome your feedback!

Overall, everything is looking far more professional and a lot more optimised. Excellent work! I think that releasing this as Kipet 2.0 makes a lot of sense.

**Review by mchlshort — APPROVED** [review]

**Comment by kwmcbride** [comment]
Thanks for the review. I have rewritten a lot of the documentation. I could also help with getting it up on the readthedocs site if you could show me how to access it.

**Comment by mchlshort** [comment]
Hi @kwmcbride I have made an update to the readthedocs. Do you have an account on there? If so, please let me know your username and I will add you to the list of maintainers.

**Comment by kwmcbride** [comment]
I have an account there. I am kwm100.

**Comment by mchlshort** [comment]
I added you as a maintainer. Hopefully this is all that was needed!

**Pull request merged**
