### PR TITLE
Estimation

### PR DESCRIPTION
**Pull request by kwmcbride**
This is the estimability method as developed by Weifeng Chen and Prof. Biegler in a recently accepted paper. The new module EstimationPotential contains the entire method and two examples from the paper are presented. Both are from the paper mentioned above. One is a CSTR model using simulated temperate profiles as experimental data. The second is the Dow Chemical problem in modified form. The latter is stiff and requires a good initialization to work with the EstimationPotential module.

The Estimation module takes the TemplateBuilder instance as an argument, along with experimental data. You have the option of adding simulated data for initialization as well. This can be seen in the examples.

Several additional changes were made to the code to make this possible, primarily in TemplateBuilder, where complementary state data can now be entered as easily as concentration data and used in estimability analysis. This was necessary for the CSTR problem.

In addition to this, I have made many changes to TemplateBuilder to reduce redundant code and make it generally cleaner. I am not done in this regard, but at the moment it looks much better.

PyomoSimulator has an additional class that replaces parameters in the ode expressions: Pi ==> Ki*Pi - where Pi is parameter i and Ki is the constant i such that Pi is unity. This is done such that the estimability follows the same methodology used by W. Chen. This was done such that the user does not need to consider this when typing up the model.

### CODE REVIEW

**Comment by mchlshort** [comment]
Hi @kwmcbride, I am very happy to review, but I will only get to it on the weekend. It looks great! Looking forward to going through it.

**Comment by kwmcbride** [comment]
I hope you like the changes!

I should also note that you can add experimental data such as temperature and concentration data taken at different times. I was using 25 temperature points with three concentration measurements as an example. These are automatically taken into consideration for discretization and in the objective function.

**Comment by schenkch** [comment]
@kwmcbride First of all, welcome to the KIPET team. =) Looks like some great effort but it seems to me like you deleted a lot of code. I did not check it in detail but did you run the full unittest and it was successful? I had the feeling that you did not just delete redundant code. Anyway I think it would be good to release the current version here https://github.com/salvadorgarciamunoz/kipet/releases before merging all this into the main version.

**Comment by kwmcbride** [comment]
@schenkch Thanks! I actually did not run the full unittest. I am doing that now and will report back the results. I only ran the validate_installation.py previously.

**Comment by schenkch** [comment]
The validate_installation was just for the user to test because to run the full test takes quite a bit of time. It just includes examples with the main software components to check whether the installation was successful. 
Whenever you want to merge something you should always run the full test, so at least the validate_tut_problems one to make sure that all the examples are still working.

**Comment by kwmcbride** [comment]
I ran validation_script.py and everything passed.

**Comment by schenkch** [comment]
That is good news but this script just checks the examples from the original paper and not the tutorial examples. You should rather check the validate_tut_problems one.

**Comment by kwmcbride** [comment]
I am running that now!

**Comment by kuanhanl** [comment]
Hi @kwmcbride, please run the validation_script.py as well!

**Comment by kwmcbride** [comment]
All tests passed except for the two new examples I added. I am checking why they did not pass. All other 61 examples were fine.

**Comment by kwmcbride** [comment]
> Hi @kwmcbride, please run the validation_script.py as well!

I already did. I have run validation_script and validation_tut. Everything is fine except the new module EstimationPotential is not found during validation of the two new examples for some reason. I am looking into that now.

Okay, my pythonpath was being overwritten somehow. I am running the tests again because I don't think they were using my modified modules.

**Comment by kwmcbride** [comment]
Sorry about the spam, but I realized that the version of TemplateBuilder in this branch is based on the version in newestim and not master. That's why many parts are missing, such as the initparameter parts. I will go back, correct this and make a new request.

**Comment by kwmcbride** [comment]
Okay, I got on the right branch for TemplateBuilder and added the Pinit parts that were missing. I have removed a couple of typos and successfully run all tests on validate_tut_problems and validation_script.

I'll start now making the examples conform to the standard format with documentation as well.

**Comment by kwmcbride** [comment]
Okay, sorry about all of that, but everything is ready for review now.

**Review by mchlshort — APPROVED** [review]
Hi Kevin, all the tests seem to be good for me and going through the code it all makes sense. Well done on all the changes! It looks great.

**Comment by schenkch** [comment]
Great job, everyone! I just added a couple of things to the release that were missing and were made since the last release.

**Pull request merged**
